### ISSUE TITLE
Default domains

### ISSUE THREAD

**Issue by vojtasvoboda** [10w042/email-autocomplete#10]
Can I add some domains to default domains list and send PR?
Or you want to keep default domains simple?

Thanks for reply
Vojta

**Comment by 10w042** [comment]
@vojtasvoboda The default domains are pretty outdated, I'm considering reducing it to just a couple in future. What domains are you intending to add?

**Comment by vojtasvoboda** [comment]
Just two biggest mail providers in Czech Republic: seznam.cz and centrum.cz

**Comment by 10w042** [comment]
That seems too country-specific, in sight of including domains such as gmail and outlook only in the future. I would suggest you add it using the domains options. Thanks!
