### ISSUE TITLE
Suggestion input remains visible if user clicks out of field

### ISSUE THREAD

**Issue by egmfrs** [10w042/email-autocomplete#11]
For example if @gmail.com is an autocomplete suggestion when the user types "myname@gm"
The user sees the additional "ail.com" in grey next to it and thinks they can click in the next field to accept this. The field value then appears potentially complete when it is not (OK the last bit is in grey but the user still thinks all is well.)

How can we make it so the suggestion is automatically accepted when they click into the next field? (As if the user had pressed tab or right arrow to accept.)
Alternatively how can we make the suggested portion disappear if the user clicks out of the field prematurely?

Many thanks

**Comment by 10w042** [comment]
Hi @egmfrs, the suggestion should autocomplete when you click on a different field, if not it might be a bug. Can you run the demo in the README on the affected system and provide me with more details on the browser (vendor, version) and platform (android, windows)?

**Comment by egmfrs** [comment]
@10w042 hmm.. it works in the demo so not sure why not for me. I'm using Chrome on Windows 10 and it's within a .net core app using bootstrap and jquery validate + validate.unobtrusive.
I overcame it by adding this to bind events section:
`this.$field.on("focusout.eac", $.proxy(this.autocomplete, this));`

**Comment by 10w042** [comment]
@egmfrs Could this be related to #12 ?

**Comment by egmfrs** [comment]
I don't see how, as it happened regardless of casing used (i.e. all my domains are lowercase and it happens when I have type in an email address in all lowercase.)
Thanks for fixing #12

**Comment by egmfrs** [comment]
Thanks @10w042 - that's worked
