### ISSUE TITLE
Suggestions are case sensitive

### ISSUE THREAD

**Issue by egmfrs** [10w042/email-autocomplete#12]
We have users who think there are capital letters in their email addresses. So they may type `MyName@G..` expecting `Gmail.com` to be suggested but it wouldn't. I did have a function to force lowercase entry into the field however this might be confusing for the user who thinks they are being prevented from typing their email address as it should be.

My own solution was to use `toLowerCase()` on lines 89 and 92:
```
      var match = this._domains.filter(function (domain) {
        return 0 === domain.indexOf(str.toLowerCase()); //use lowercase for case insensitive search
      }).shift() || "";

      return match.replace(str.toLowerCase(), "");      //also force lowercase matching here to ensure typed text is not prepended to the autocomplete suggestion
                                                        //(example; @GOOgooglemail.com)
```
There may be a better way of doing it? Although I like that this way preserves the casing that the user wants.

**Comment by 10w042** [comment]
This is indeed an issue that needs fixing, and kudos for highlighting this! Your suggestion sounds good, let me patch it up.
