### ISSUE TITLE
Newest version matches dot to any character

### ISSUE THREAD

**Issue by Ruud-Zuiderlicht** [10w042/email-autocomplete#14]
Newest version (not in demo) matches a dot to any character. Pressing enter afterwards leaves the dot in. So "@gma.l" matches "gmail.com". Pressing enter when @gma.l in in the input completes the field to @gma.l.com.

Probably a problem with this line: https://github.com/10w042/email-autocomplete/blob/master/src/jquery.email-autocomplete.js#L90

**Comment by 10w042** [comment]
I've reverted to using indexOf. This should fix the issue. Thanks for highlighting!
