### ISSUE TITLE
Text overlap

### ISSUE THREAD

**Issue by nhanhv** [10w042/email-autocomplete#9]
Hi guy,

First I want to say thanks for your plugin. 
Next, I have apply your plugin to my example and found an issue. 
Please look it [http://pix.toile-libre.org/upload/original/1474452273.png](url)
I hope you will fix it soon. 

Thanks!

**Comment by 10w042** [comment]
@nhanhv Thanks. Can you explain why you closed the issue?

**Comment by nhanhv** [comment]
Yes, I can.

This happening when I custom font size for **suggestion class(.eac-sugg)** larger **.eac-cval** class, but position of **suggestion text** follow the width of .**eac-cval**, so text will be overlap. Final, I custom style for **.eac-cval** the same **suggestion class(.eac-sugg)**, and it is fine.

Thanks

**Comment by 10w042** [comment]
@nhanhv Apologies for the slow response, thanks for your explanation. :)
